# Generated by Django 3.2.5 on 2022-05-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True, verbose_name='产品系列')),
                ('input_date', models.DateTimeField(verbose_name='入库日期')),
                ('output_date', models.DateTimeField(verbose_name='出库日期')),
            ],
            options={
                'verbose_name': 'Mes产品系列信息',
                'verbose_name_plural': 'Mes产品系列信息',
                'db_table': 'Mes_server',
                'ordering': ['-input_date'],
            },
        ),
        migrations.CreateModel(
            name='Fireware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='服务器SN')),
                ('system_sn', models.CharField(max_length=50, verbose_name='系统序列号')),
                ('system_vendor', models.CharField(max_length=30, verbose_name='系统制造商')),
                ('system_version', models.CharField(max_length=25, verbose_name='系统版本')),
                ('bois_version', models.CharField(max_length=25, verbose_name='BIOS版本')),
                ('bmc_version', models.CharField(max_length=25, verbose_name='BMC版本')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkApp.mes_server', verbose_name='产品系列')),
            ],
            options={
                'verbose_name': '固件信息',
                'verbose_name_plural': '固件信息',
                'db_table': 'Fireware',
            },
        ),
    ]
