# Generated by Django 3.2.5 on 2022-05-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, unique=True, verbose_name='服务器SN')),
                ('type', models.CharField(max_length=50, verbose_name='CPU型号')),
                ('architecture', models.CharField(max_length=20, verbose_name='CPU架构')),
                ('core_number', models.IntegerField(max_length=10, verbose_name='CPU核数')),
                ('thread_number', models.IntegerField(max_length=10, verbose_name='CPU线程数')),
                ('speed', models.CharField(max_length=20, verbose_name='CPU主频')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkApp.mes_server', verbose_name='产品系列')),
            ],
            options={
                'verbose_name': 'CPU信息',
                'verbose_name_plural': 'CPU信息',
                'db_table': 'CPU',
            },
        ),
    ]
