# Generated by Django 3.2.5 on 2022-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkApp', '0002_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='服务器SN'),
        ),
    ]
