# Generated by Django 3.2.5 on 2022-03-05 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, verbose_name='服务器SN')),
                ('worker', models.IntegerField(max_length=10, verbose_name='工号')),
                ('ip', models.CharField(max_length=30, verbose_name='IP号')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'ordering': ['-submission_date'],
            },
        ),
    ]
