# Generated by Django 3.2.5 on 2022-05-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=30, verbose_name='服务器SN')),
                ('ip', models.CharField(max_length=30, verbose_name='IP号')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='工号')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
                'db_table': 'Servers',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='SubmitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, null=True, verbose_name='日志')),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serversApp.servers', verbose_name='服务器SN')),
            ],
            options={
                'verbose_name': '日志信息',
                'verbose_name_plural': '日志信息',
                'db_table': 'SubmitLog',
                'ordering': ['-log_date'],
            },
        ),
    ]
