# Generated by Django 3.2.5 on 2022-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitlog',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='日志'),
        ),
    ]
