# Generated by Django 3.2.5 on 2022-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='worker',
            field=models.CharField(max_length=10, verbose_name='工号'),
        ),
        migrations.AlterModelTable(
            name='server',
            table='Server',
        ),
    ]
