# Generated by Django 3.2.5 on 2022-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serversApp', '0003_alter_submitlog_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitlog',
            name='log',
        ),
        migrations.AddField(
            model_name='submitlog',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文件存放路径'),
        ),
    ]
